// Chaque antenne a son compte kiosk pour le poste de pointage :

// Antenne	Ville	Login kiosk	Mot de passe
// Antenne Abidjan	Abidjan	kiosk-abidjan	kiosk123
// Antenne Bouake	Bouake	kiosk-bouake	kiosk123
// Antenne Yamoussoukro	Yamoussoukro	kiosk-yakro	kiosk123
// Antenne San Pedro	San Pedro	kiosk-sanpedro	kiosk123

// Comptes utilisateurs
// Identifiant	Mot de passe	Role	Antenne
// admin	admin123	Super Admin	Abidjan
// resp.abidjan	resp123	Responsable	Abidjan
// resp.bouake	resp123	Responsable	Bouake
// ibrahim.k	employe123	Employe	Abidjan
// fatou.t	employe123	Employe	Abidjan
// jean.o	employe123	Employe	Bouake
// + 3 autres...
